_target_: src.models.SITSLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

model:
  _target_: src.models.components.TSViT.TSViT
  # num_features: 6
  # hidden_channel: 32
  # kernel_size: 3
  # hidden_size1: 32
  # hidden_size2: 32
  # num_layers: 3
  # dropout: 0.1