_target_: src.models.SITSLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

model:
  _target_: src.models.components.CNN_3D.CNN_3D
  num_features: 6
  hidden_channel: 64
  kernel_size: 3
  hidden_size1: 128 
  hidden_size2: 64 
  num_layers: 1 