_target_: src.datamodules.SITSDataModule
data_dir: ${paths.data_dir}
metadata_train_path: ${paths.data_dir}/Crop_Yield_Data_challenge_2.csv
metadata_test_path: ${paths.data_dir}/Challenge_2_submission_template.csv
data_train_path1: ${paths.data_dir}/train_sentinel1_normalized1.nc
data_train_path2: ${paths.data_dir}/train_sentinel1_normalized2.nc
data_test_path: ${paths.data_dir}/test_sentinel1_normalized2.nc
train_val_test_split: [0.9, 0.05, 0.05]
bands: ["vv", "vh", "vv_by_vh", "vv_add_vh", "DOP", "RVI"]
batch_size: 32
num_workers: 0
pin_memory: False